version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: weather-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: weather
    ports:
      - "5432:5432"